set( opencv_CMake_args
     -G "Ninja"
     -DCMAKE_BUILD_TYPE=Release
     -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
     -DANDROID_NDK=${ANDROID_NDK}
     -DANDROID_SDK=${ANDROID_SDK_ROOT}
     -DCMAKE_INSTALL_PREFIX=${THIRD_PARTY_INSTALL_DIR}/opencv
     -DANDROID_ABI=${ANDROID_ABI}
     -DANDROID_NATIVE_API_LEVEL=${ANDROID_NATIVE_API_LEVEL}
     -DBUILD_SHARED_LIBS=OFF # build static lib
     #-DANDROID_ARM_NEON=ON
     #-DENABLE_NEON=ON
     -DANDROID_TOOLCHAIN=clang
     -DBUILD_ANDROID_PROJECTS=OFF
     -DBUILD_TESTS=OFF
     -DBUILD_PERF_TESTS=OFF
     -DBUILD_EXAMPLES=OFF
     -DBUILD_opencv_apps=OFF
     -DINSTALL_PYTHON_EXAMPLES=OFF
     -DINSTALL_C_EXAMPLES=OFF
     )
if( UNIX )
	set( opencv_CMake_args ${opencv_CMake_args} -DCMAKE_CXX_FLAGS=-fPIC )
endif()